/*
 * Popup killer: MAIN world, every http(s) page and its about:blank frames,
 * document_start.
 *
 * Popunders survive plain window.open() trapping. The payload behind vfxmed.com
 * (PopAds deployment script) opens its windows from a HIDDEN IFRAME
 * ("this.iframewin.open('about:blank', ...)"), so wrapping the top window's
 * open() catches nothing, then blanks the window and writes the ad into it, so
 * URL rules have no URL to match. It also installs a transparent full-viewport
 * div that turns the first click anywhere into the trigger, and shows a
 * "disable your popup blocker" screen when its window is refused.
 *
 * Doors closed here:
 *   R1 host on the generated blocklist, or a script caught as a loader -> veto
 *   R2 call made from a hidden frame, or the popup itself is about:blank and
 *      frame-sized -> veto
 *   R3 no live user activation (timer, auto-click, delayed trigger)      -> veto
 *   R4 page already flagged as an ad page                                -> veto
 *   R5 the transparent click-catcher and the blocker blackmail screen are
 *      removed by structure, and <script> tags disguised as .css are refused.
 * Anything else passes untouched, and the module can be disarmed plus given a
 * per-site allowlist by src/relay.js over postMessage. Hosts caught in the wild
 * are reported up so the service worker can block them network-wide.
 */
(() => {
  'use strict';

  const CHANNEL = 'yt-ad-zapper';
  const DEBUG = true;
  const TAG = '[yt-ad-zapper]';
  const REPORT_CAP = 60;
  // One newline-delimited string, generated by tools/build-popup-list.mjs. This
  // file runs in every frame of every page, and thousands of separate JS strings
  // in a Set cost hundreds of KB of heap per frame; one packed string costs the
  // list size and nothing else.
  const HOST_LIST = typeof self.__yazPopupHosts === 'string' ? self.__yazPopupHosts : '\n';
  const HOST_COUNT = Number(self.__yazPopupHostCount) || 0;
  // The loader disguise: a <script> whose path ends in .css. No real site does
  // this; the ad payloads serve JavaScript from ".../zgettext.cjs.min.css".
  const CSS_SCRIPT = /\.css$/i;
  // Loader body signatures, in case a fresh host serves the payload inline.
  const LOADER_BODY = /popundersPerIP|topmostLayer|zgettext|pgettext|\.cjs\.min\.css|rsha256|bsha256/i;
  // The blocker blackmail screen, straight out of the payload's source.
  const BLACKMAIL = /popup blocker|blocker[^.!?]{0,40}(disable|turn off)|disable[^.!?]{0,40}blocker/i;
  // Their click-catcher: inline "position:fixed" with a five-or-more digit
  // z-index. Their window layer uses ids and classes with these stems.
  const OVERLAY_STYLE = /position\s*:\s*fixed[\s\S]{0,400}?z-index\s*:\s*\d{5,}/i;
  const OVERLAY_MARK = /c_window_|a_timer_|alink_overlay_|a_close_/i;

  let armed = true;
  let suspect = false;
  let allowlist = [];
  let reports = 0;
  const escalated = new Set();

  const log = (...args) => {
    if (DEBUG) console.log(TAG, ...args);
  };

  // Suffix match against the packed list: walk the host's labels and test each
  // one with a newline-padded substring search. Lookups only happen on
  // window.open() calls and script insertions, so this is nothing next to the
  // heap the per-frame Set used to cost.
  //
  // Every candidate goes through the shipped Bloom filter first: a miss is a
  // definite no, so the string search only runs on the ~1% that slip through.
  // Without it a lookup costs ~36 µs of scanning; with it, a miss costs ~1 µs.
  const FILTER = (() => {
    try {
      const encoded = typeof self.__yazPopupBits === 'string' ? self.__yazPopupBits : '';
      const count = Number(self.__yazPopupBitCount) || 0;
      if (!encoded || !count || typeof atob !== 'function') return null;
      const raw = atob(encoded);
      const bytes = new Uint8Array(raw.length);
      for (let index = 0; index < raw.length; index++) bytes[index] = raw.charCodeAt(index);
      if (bytes.length * 8 < count) return null;
      // The bits are the only thing worth keeping: drop the base64 text so it is
      // not held for the life of the frame.
      try {
        self.__yazPopupBits = '';
        self.__yazPopupBitCount = 0;
      } catch (_) {}
      return { bytes, count };
    } catch (_) {
      return null;
    }
  })();
  const hashHost = typeof self.__yazPopupHash === 'function' ? self.__yazPopupHash : null;

  const maybeListed = (host) => {
    if (FILTER === null || hashHost === null) return true;
    const hash = hashHost(host);
    const first = hash % FILTER.count;
    const second = (hash >>> 16) % FILTER.count;
    return (
      (FILTER.bytes[first >> 3] & (1 << (first & 7))) !== 0 &&
      (FILTER.bytes[second >> 3] & (1 << (second & 7))) !== 0
    );
  };

  const listed = (host) => {
    let h = String(host || '').toLowerCase();
    if (!h) return false;
    for (;;) {
      if (maybeListed(h) && HOST_LIST.includes('\n' + h + '\n')) return true;
      const dot = h.indexOf('.');
      if (dot < 0) return false;
      h = h.slice(dot + 1);
    }
  };
  const allowed = (host) => allowlist.some((d) => host === d || host.endsWith('.' + d));

  const report = (kind, details) => {
    reports++;
    if (reports > REPORT_CAP) return;
    try {
      window.postMessage({ source: CHANNEL, type: 'popup-blocked', kind, ...details }, '*');
    } catch (_) {}
  };

  // Every host we actually catch becomes a network-level block, once.
  const escalate = (host) => {
    const clean = String(host || '').toLowerCase();
    if (!clean || !clean.includes('.') || escalated.has(clean)) return;
    escalated.add(clean);
    try {
      window.postMessage({ source: CHANNEL, type: 'escalate', host: clean }, '*');
    } catch (_) {}
    log('handing host to the network layer', clean);
  };

  // Config from src/relay.js: armed flag plus the per-site allowlist.
  window.addEventListener('message', (event) => {
    if (event.source !== window) return;
    const data = event.data;
    if (!data || data.source !== CHANNEL || data.type !== 'config') return;
    if (typeof data.arm === 'boolean') armed = data.arm;
    if (Array.isArray(data.allowlist)) allowlist = data.allowlist.map((d) => String(d).toLowerCase());
  });

  const parse = (rawUrl) => {
    try {
      const url = new URL(String(rawUrl), location.href);
      if (url.protocol !== 'http:' && url.protocol !== 'https:') return null;
      if (url.origin === location.origin) return null;
      return url;
    } catch (_) {
      return null;
    }
  };

  const activation = () => {
    const ua = navigator.userActivation;
    if (!ua) return 'unknown';
    if (ua.isActive) return 'active';
    return ua.hasBeenActive ? 'expired' : 'never';
  };

  // A frame with no visible box has no legitimate reason to open windows.
  const ownFrameHidden = () => {
    try {
      if (window === window.top) return false;
      const element = window.frameElement;
      if (element) {
        const rect = element.getBoundingClientRect();
        if (!rect || rect.width < 20 || rect.height < 20) return true;
        const style = getComputedStyle(element);
        return style.display === 'none' || style.visibility === 'hidden' || Number(style.opacity) === 0;
      }
      return window.innerWidth === 0 || window.innerHeight === 0;
    } catch (_) {
      return false;
    }
  };

  // The same test applied to the window that made the call, which is how the
  // top frame sees a same-origin hidden iframe.
  const callerHidden = (holder) => {
    try {
      if (!holder || holder === window) return false;
      return holder.innerWidth === 0 && holder.innerHeight === 0;
    } catch (_) {
      return false;
    }
  };

  const hiddenCaller = (holder) => {
    try {
      if (callerHidden(holder)) return true;
      return window !== window.top && ownFrameHidden() && holder === window;
    } catch (_) {
      return false;
    }
  };

  const isBlank = (raw) => {
    const value = String(raw === undefined || raw === null ? 'about:blank' : raw).trim().toLowerCase();
    return value === '' || value === 'about:blank' || value.includes('javascript:');
  };

  // Returns a verdict object when the call should be dropped, null to allow it.
  const decideOpen = (rawUrl, holder) => {
    if (!armed) return null;
    if (isBlank(rawUrl)) {
      if (hiddenCaller(holder)) return { host: '(blank)', url: 'about:blank', why: 'popup from a hidden frame' };
      if (suspect) return { host: '(blank)', url: 'about:blank', why: 'blank popup on an ad page' };
      return null;
    }
    const url = parse(rawUrl);
    if (url === null) return null;
    const host = url.hostname.toLowerCase();
    if (allowed(host)) return null;
    if (listed(host)) return { host, url: url.href, why: 'host on the popup blocklist' };
    if (hiddenCaller(holder)) return { host, url: url.href, why: 'popup from a hidden frame' };
    if (suspect) return { host, url: url.href, why: 'popup on an ad page' };
    if (activation() === 'expired') return { host, url: url.href, why: 'no user gesture' };
    return null;
  };

  const flagSuspect = (why) => {
    if (suspect) return;
    suspect = true;
    log('page flagged as an ad page:', why);
  };

  // Patching the instance alone misses iframe.contentWindow.open(), which is
  // exactly the route the payload uses, so patch the holder of the property.
  const wrapOpen = (holder) => {
    let descriptor = null;
    try {
      descriptor = Object.getOwnPropertyDescriptor(holder, 'open');
    } catch (_) {
      return false;
    }
    if (!descriptor || typeof descriptor.value !== 'function') return false;
    const nativeOpen = descriptor.value;
    const open = function (url, ...rest) {
      let verdict = null;
      try {
        verdict = decideOpen(url, this);
      } catch (_) {
        verdict = null;
      }
      if (verdict !== null) {
        log('popup blocked:', verdict.why, verdict.url);
        report('popup', verdict);
        if (verdict.why.startsWith('popup on') || verdict.why.startsWith('popup from')) flagSuspect('popup attempt');
        return null;
      }
      return Reflect.apply(nativeOpen, this, [url, ...rest]);
    };
    try {
      Object.defineProperty(holder, 'open', {
        value: open,
        writable: true,
        enumerable: descriptor.enumerable,
        configurable: true
      });
      return true;
    } catch (_) {
      try {
        holder.open = open;
        return true;
      } catch (_) {
        return false;
      }
    }
  };

  const patchedInstance = wrapOpen(window);
  let patchedPrototype = false;
  try {
    const proto = Object.getPrototypeOf(window);
    if (proto && proto !== window) patchedPrototype = wrapOpen(proto);
  } catch (_) {}

  // Script insertions: blocklisted hosts, and JavaScript wearing a .css path.
  const vetoScript = (node) => {
    if (!armed || !node || node.nodeType !== 1 || String(node.tagName).toUpperCase() !== 'SCRIPT') return false;
    const src = node.src || (typeof node.getAttribute === 'function' ? node.getAttribute('src') : null);
    if (!src) {
      let body = '';
      try {
        body = node.textContent || '';
      } catch (_) {}
      if (body && LOADER_BODY.test(body)) {
        flagSuspect('inline loader body');
        report('loader', { host: location.hostname, url: 'inline loader' });
        return true;
      }
      return false;
    }
    const url = parse(src);
    if (url === null) return false;
    const host = url.hostname.toLowerCase();
    if (allowed(host)) return false;
    if (listed(host)) {
      flagSuspect('script from a blocklisted host');
      report('script', { host, url: url.href });
      escalate(host);
      return true;
    }
    if (CSS_SCRIPT.test(url.pathname)) {
      flagSuspect('script disguised as css');
      report('loader', { host, url: url.href });
      escalate(host);
      return true;
    }
    return false;
  };

  // Overlay handling: the click-catcher goes away, the blackmail screen goes
  // away, and either one flags the page.
  const coversViewport = (element) => {
    try {
      const rect = element.getBoundingClientRect();
      if (!rect) return false;
      const width = Math.max(1, window.innerWidth);
      const height = Math.max(1, window.innerHeight);
      return rect.width >= width * 0.6 && rect.height >= height * 0.5;
    } catch (_) {
      return false;
    }
  };

  const strip = (element, reason, url) => {
    log('removing', reason);
    report('overlay', { host: location.hostname, url });
    try {
      element.style.setProperty('pointer-events', 'none', 'important');
    } catch (_) {}
    try {
      element.remove();
    } catch (_) {}
  };

  const inspect = (element) => {
    try {
      if (!element || element.nodeType !== 1 || !element.isConnected) return;
      const id = String(element.id || '');
      const className = typeof element.className === 'string' ? element.className : '';
      const style = (element.getAttribute && element.getAttribute('style')) || '';
      const marked = OVERLAY_MARK.test(id) || OVERLAY_MARK.test(className);
      if (!marked && !OVERLAY_STYLE.test(style)) return;

      let text = '';
      try {
        text = (element.textContent || '').slice(0, 400);
      } catch (_) {}

      if (BLACKMAIL.test(text)) {
        flagSuspect('blocker blackmail screen');
        strip(element, 'popup blocker blackmail screen', 'blocker screen');
        return;
      }
      if (marked) {
        flagSuspect('ad window layer');
        strip(element, 'ad window layer', id || className);
        return;
      }
      if (!coversViewport(element)) return;
      const transparent = /rgba\(\s*0\s*,\s*0\s*,\s*0\s*,\s*0\s*\)|background(-color)?\s*:\s*transparent/i.test(style);
      if (!transparent) return;
      flagSuspect('transparent click catcher');
      strip(element, 'transparent click catcher', 'click catcher');
    } catch (_) {}
  };

  const queued = new WeakSet();
  const schedule = (element) => {
    try {
      if (!element || element.nodeType !== 1) return;
      const id = String(element.id || '');
      const className = typeof element.className === 'string' ? element.className : '';
      const style = (element.getAttribute && element.getAttribute('style')) || '';
      if (!OVERLAY_MARK.test(id) && !OVERLAY_MARK.test(className) && !OVERLAY_STYLE.test(style)) return;
      if (queued.has(element)) return;
      queued.add(element);
      setTimeout(() => {
        queued.delete(element);
        inspect(element);
      }, 0);
    } catch (_) {}
  };

  const vetoInsert = (node) => {
    if (!armed || !node || node.nodeType !== 1) return false;
    if (vetoScript(node)) return true;
    schedule(node);
    return false;
  };

  const patchInsert = (proto, name) => {
    if (!proto || typeof proto[name] !== 'function') return;
    const original = proto[name];
    const wrapped = function (...args) {
      if (vetoInsert(args[0])) return args[0];
      return Reflect.apply(original, this, args);
    };
    try {
      Object.defineProperty(proto, name, { value: wrapped, writable: true, configurable: true });
    } catch (_) {
      try {
        proto[name] = wrapped;
      } catch (_) {}
    }
  };

  patchInsert(Node.prototype, 'appendChild');
  patchInsert(Node.prototype, 'insertBefore');

  // The observer catches what the insert patches miss: parser-inserted loader
  // scripts, their <style> blocks, and the click-catcher once the payload
  // restyles it into a blackmail screen.
  const startObserver = () => {
    try {
      const observer = new MutationObserver((mutations) => {
        if (!armed) return;
        for (const mutation of mutations) {
          if (mutation.type === 'attributes') {
            schedule(mutation.target);
            continue;
          }
          for (const node of mutation.addedNodes) {
            if (!node) continue;
            if (node.nodeType === 1) {
              if (String(node.tagName).toUpperCase() === 'SCRIPT' && !node.src) vetoScript(node);
              if (String(node.tagName).toUpperCase() === 'STYLE') {
                let css = '';
                try {
                  css = node.textContent || '';
                } catch (_) {}
                if (OVERLAY_MARK.test(css)) flagSuspect('ad payload stylesheet');
              }
              schedule(node);
            } else if (node.nodeType === 3) {
              const parent = node.parentElement;
              const text = node.nodeValue || '';
              if (parent && text && BLACKMAIL.test(text)) {
                flagSuspect('blocker blackmail screen');
                strip(parent, 'popup blocker blackmail screen', 'blocker screen');
              }
            }
          }
        }
      });
      observer.observe(document.documentElement || document, {
        childList: true,
        subtree: true,
        attributes: true,
        attributeFilter: ['style']
      });
    } catch (_) {}
  };

  startObserver();

  log(
    `popup killer armed: ${HOST_COUNT} hosts, ${HOST_LIST.length} bytes, filter=${FILTER ? `${FILTER.count} bits` : 'off'}, instance=${patchedInstance}, prototype=${patchedPrototype}`
  );
})();
