/*
 * Generated by tools/build-replace-rules.mjs. Do not edit.
 *
 * Hosts whose responses this extension rewrites, which is the set of sites
 * that try to wall readers out. src/wall-guard.js loads this in every frame
 * and returns immediately unless the frame is on one of them.
 */
self.__yazWallHosts = "\nbild.de\ncdn.greenvideo.io\ncdn.player.foundation\ncinema.de\ndailymail.co.uk\ndailymail.com\nfacebook.com\nglobal.novelpia.com\ngolem.de\npvpoke-re.com\nstatic.veevcdn.co\nstatic.xx.fbcdn.net\nsvonm.com\nwelt.de\nwww.youtube.com\nyoutube.com\n";
self.__yazWallHostCount = 16;
